#!/usr/bin/env python3
"""
Generates tools/seed/test1_games.sql: four opponents and 18 confirmed own games (with warband lists) for the
existing user "test1", so the profile statistics have data. Deterministic (fixed random seed) and re-runnable:
the SQL first removes games it created earlier (notes = '[seed]').

Usage:  python3 tools/seed/make_test1_games.py
Run:    docker compose exec -T postgres psql -U skirmish -d skirmish < tools/seed/test1_games.sql
"""
import datetime
import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARMIES = json.loads((ROOT / "backend/src/main/resources/content/eldfall-armies.json").read_text(encoding="utf-8"))
OUT = ROOT / "tools/seed/test1_games.sql"

rng = random.Random(20260926)
units = {u["code"]: u for u in ARMIES["units"]}
items = {i["code"]: i for i in ARMIES["items"]}
factions = {f["code"]: f for f in ARMIES["factions"]}
QUESTS = [q["code"] for q in json.loads((ROOT / "backend/src/main/resources/content/eldfall-core.json")
                                        .read_text(encoding="utf-8"))["quests"]]


def pool(faction, allied):
    f = factions[faction]
    codes = []
    for src in [faction, *f["alwaysAvailable"], *([allied] if allied else [])]:
        for c in ARMIES["lists"].get(src, []):
            if c not in codes:
                codes.append(c)
    return codes


def item_pool(faction):
    lists = ARMIES["itemLists"]
    return list(dict.fromkeys(lists.get("NEUTRAL", []) + lists.get(faction, [])))


def make_list(faction, allied=None, core=()):
    codes = pool(faction, allied)
    chosen = [c for c in core if c in codes]
    rest = [c for c in codes if c not in chosen]
    rng.shuffle(rest)
    chosen += rest[: max(0, rng.randint(3, 4) - len(chosen))]
    ipool = item_pool(faction)
    out, total = [], 0
    for i, c in enumerate(chosen):
        its = []
        for code in rng.sample(ipool, k=rng.choice([0, 0, 1, 1, 2])) if ipool else []:
            its.append({"item": code, "reduced": False})
            total += items[code]["points"]
        total += units[c]["points"]
        out.append({"unit": c, "leader": i == 0, "items": its})
    return {"faction": faction, "alliedFaction": allied, "units": out, "totalPoints": total}


# test1 mostly plays Oni (with Undead) and sometimes Helian or Sand; core characters make the top-5 meaningful.
MY_SETUPS = [
    ("ONI_CLANS", "UNDEAD", ["CHIYOHIME", "RED_RASETSU"]),
    ("ONI_CLANS", "UNDEAD", ["CHIYOHIME", "ONI_MARAUDER"]),
    ("ONI_CLANS", None, ["BLUE_YAKSHA", "RED_RASETSU"]),
    ("HELIAN_LEAGUE", None, ["PALADIN_OF_THE_ORDER", "AMAZON_GLADIATRIX"]),
    ("SAND_KINGDOMS", None, ["NARA_VEIL_WATCHER", "TASKMAGE_EXPLORER"]),
]
OPPONENTS = {
    "Aldric": [("COALITION_OF_THENION", None, []), ("EMPIRE_OF_SOGA", None, ["GREAT_GUARD"])],
    "Brena": [("HELIAN_LEAGUE", None, ["FLAMEWEAVER_NOBLE"])],
    "Cador": [("GOBLIN_WARTRIBES", None, []), ("ADVENTURERS_GUILD", None, ["AMAZON_GLADIATRIX"])],
    "Dara": [("EMPIRE_OF_SOGA", None, ["GREAT_GUARD", "CLAN_CHAMPION"]), ("SAND_KINGDOMS", None, [])],
}
WEIGHTS = [5, 4, 3, 2, 2]

games = []
today = datetime.date(2026, 9, 25)
for n in range(18):
    opp = list(OPPONENTS)[n % 4]
    mine = make_list(*rng.choices(MY_SETUPS, weights=WEIGHTS)[0])
    theirs = make_list(*rng.choice(OPPONENTS[opp]))
    a, b = rng.randint(0, 10), rng.randint(0, 10)
    if n % 5 == 0:
        b = a  # a few draws
    played = today - datetime.timedelta(days=4 + n * 6 + rng.randint(0, 3))
        # Mostly a recorded mission, weighted so the chart has favourites; now and then none.
    quest = None if n % 7 == 6 else rng.choices(QUESTS, weights=[5, 4, 4, 3, 2, 2, 1][: len(QUESTS)])[0]
    games.append((opp, a, b, played, quest, mine, theirs, n % 3 == 0))


def q(v):
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


lines = [
    "-- Generated by tools/seed/make_test1_games.py – test data only, do not run in production.",
    "DO $$",
    "DECLARE",
    "    me UUID;",
    "    opp UUID;",
    "    reporter UUID;",
    "BEGIN",
    "    SELECT id INTO me FROM users WHERE lower(display_name) = 'test1';",
    "    IF me IS NULL THEN",
    "        RAISE EXCEPTION 'Brak użytkownika test1 – najpierw załóż konto o tym nicku.';",
    "    END IF;",
    "    DELETE FROM friendly_games WHERE notes = '[seed]' AND (player_a = me OR player_b = me);",
]
for name in OPPONENTS:
    lines += [
        f"    SELECT id INTO opp FROM users WHERE lower(display_name) = lower({q(name)});",
        "    IF opp IS NULL THEN",
        "        opp := gen_random_uuid();",
        "        INSERT INTO users (id, email, display_name, email_verified_at, locale, created_at, updated_at)",
        f"        VALUES (opp, {q('seed-' + name.lower() + '@example.invalid')}, {q(name)}, now(), 'pl', now(), now());",
        "        INSERT INTO user_roles (user_id, role) VALUES (opp, 'USER');",
        "    END IF;",
    ]
for opp, a, b, played, quest, mine, theirs, opponent_reported in games:
    # The reporter is always player A; when the opponent reported, the scores and lists swap sides.
    if opponent_reported:
        pa, pb, sa, sb, la, lb = "opp", "me", b, a, theirs, mine
    else:
        pa, pb, sa, sb, la, lb = "me", "opp", a, b, mine, theirs
    lines += [
        f"    SELECT id INTO opp FROM users WHERE lower(display_name) = lower({q(opp)});",
        "    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,",
        "        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)",
        f"    VALUES (gen_random_uuid(), {pa}, {pb}, {sa}, {sb}, DATE {q(played.isoformat())}, {q(quest)},",
        f"        {q(la['faction'])}, {q(lb['faction'])}, NULL, '[seed]', 'CONFIRMED', {pa}, now(), now(),",
        f"        {q(json.dumps(la))}, {q(json.dumps(lb))});",
    ]
lines += ["    RAISE NOTICE 'Dodano % gier dla test1', " + str(len(games)) + ";", "END $$;", ""]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"{len(games)} games -> {OUT.relative_to(ROOT)}")
