-- Generated by tools/seed/make_stats_player.py – test data only, do not run in production.
-- Test account: seed-tester@example.invalid / DruzynyTest2026 (nick Tester).
DO $$
DECLARE
    pa UUID;
    pb UUID;
    pwd TEXT := '$argon2id$v=19$m=16384,t=2,p=1$ecJFJfDX8tXq7qgNWKm7yg$YMlEscuP0KId5BGmWRDiWQ5qDlb/QG6YCELO8qVr6YA';
BEGIN
    DELETE FROM friendly_games WHERE notes = '[seed-stats]';
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-tester@example.invalid', 'Tester', pwd, now(), 'pl', 'Klub Testowy', 'Warszawa',
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-tester@example.invalid' THEN
        RAISE EXCEPTION 'Nick Tester jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Aldric');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-aldric@example.invalid', 'Aldric', pwd, now(), 'pl', NULL, NULL,
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-aldric@example.invalid' THEN
        RAISE EXCEPTION 'Nick Aldric jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Brena');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-brena@example.invalid', 'Brena', pwd, now(), 'pl', NULL, NULL,
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-brena@example.invalid' THEN
        RAISE EXCEPTION 'Nick Brena jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Cador');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-cador@example.invalid', 'Cador', pwd, now(), 'pl', NULL, NULL,
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-cador@example.invalid' THEN
        RAISE EXCEPTION 'Nick Cador jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Dara');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-dara@example.invalid', 'Dara', pwd, now(), 'pl', NULL, NULL,
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-dara@example.invalid' THEN
        RAISE EXCEPTION 'Nick Dara jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Eryk');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-eryk@example.invalid', 'Eryk', pwd, now(), 'pl', NULL, NULL,
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-eryk@example.invalid' THEN
        RAISE EXCEPTION 'Nick Eryk jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Fenna');
    IF pa IS NULL THEN
        INSERT INTO users (id, email, display_name, password_hash, email_verified_at, locale, club, home_city,
                           created_at, updated_at)
        VALUES (gen_random_uuid(), 'seed-fenna@example.invalid', 'Fenna', pwd, now(), 'pl', NULL, NULL,
                now() - interval '200 days', now())
        RETURNING id INTO pa;
        INSERT INTO user_roles (user_id, role) VALUES (pa, 'USER');
    ELSIF (SELECT email FROM users WHERE id = pa) <> 'seed-fenna@example.invalid' THEN
        RAISE EXCEPTION 'Nick Fenna jest zajęty przez inne konto – zmień nazwę w make_stats_player.py';
    ELSE
        UPDATE users SET password_hash = coalesce(password_hash, pwd) WHERE id = pa;
    END IF;
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Dara');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 3, 6, DATE '2026-04-07', 'QUARTER_WAR',
        'EMPIRE_OF_SOGA', 'SAND_KINGDOMS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "CLAN_CHAMPION", "leader": true, "items": [{"item": "BUJUTSU_EXPERTISE", "reduced": false}]}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}, {"item": "LUCKY_CHARM", "reduced": false}]}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": [{"item": "TRAVELING_DUELIST", "reduced": false}]}], "totalPoints": 94}', '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": []}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "ARCANE_TOME", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}], "totalPoints": 63}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Fenna');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 5, 1, DATE '2026-04-15', 'TREASURE_HUNT',
        'EMPIRE_OF_SOGA', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "MUSHA_BLADEMASTER", "leader": true, "items": [{"item": "KYUJUTSU_EXPERTISE", "reduced": false}, {"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "KITSUNE_SPELLMAIDEN", "leader": false, "items": [{"item": "POUCH", "reduced": false}, {"item": "FIRST_AID", "reduced": false}]}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": [{"item": "KASSEN_BUKI_DAIKYUU_TSUKAI", "reduced": false}, {"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": [{"item": "TRAVELING_DUELIST", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "SEASONED_COMBATANT", "reduced": false}, {"item": "FIRST_AID", "reduced": false}]}], "totalPoints": 136}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": []}], "totalPoints": 40}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Eryk');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 4, 5, DATE '2026-04-26', 'CLUE_TRAIL',
        'SAND_KINGDOMS', 'ONI_CLANS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        NULL, NULL);
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Dara');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 3, 5, DATE '2026-05-06', 'QUARTER_WAR',
        'EMPIRE_OF_SOGA', 'EMPIRE_OF_SOGA', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "CLAN_CHAMPION", "leader": true, "items": [{"item": "CAMARADERIE", "reduced": false}, {"item": "TRAVELING_DUELIST", "reduced": false}]}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "HELRIN_EXPATRIATE", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}], "totalPoints": 84}', '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "MUSHA_BLADEMASTER", "leader": true, "items": []}, {"unit": "KITSUNE_SPELLMAIDEN", "leader": false, "items": []}, {"unit": "CLAN_CHAMPION", "leader": false, "items": []}, {"unit": "SEIGEN_OF_THE_KESHOBARAI", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}], "totalPoints": 85}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Fenna');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 10, 2, DATE '2026-05-14', 'QUARTER_WAR',
        'SAND_KINGDOMS', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "CONJURED_RETINUE", "reduced": false}, {"item": "PERSONAL_GUARD", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "HELRIN_EXPATRIATE", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": [{"item": "ARCANE_TOME", "reduced": false}]}, {"unit": "SPELLDANCER_VOIDCASTER", "leader": false, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 112}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": []}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "DEVOTION_PAIMON", "reduced": false}]}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": []}], "totalPoints": 57}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 7, 10, DATE '2026-05-23', NULL,
        'SAND_KINGDOMS', 'HELIAN_LEAGUE', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "SPELLDANCER_VOIDCASTER", "leader": true, "items": []}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": []}, {"unit": "HIRED_BLADE", "leader": false, "items": [{"item": "CONJURED_RETINUE", "reduced": false}]}], "totalPoints": 103}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "POUCH", "reduced": false}, {"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}, {"item": "EXPEDITIONARY_TACTICS_SURGE_ORDER", "reduced": false}]}, {"unit": "HELRIN_EXPATRIATE", "leader": false, "items": [{"item": "EXPEDITIONARY_TACTICS_DOUBLE_TIME", "reduced": false}, {"item": "ADEPT_SHAPER", "reduced": false}]}, {"unit": "ANARI_ERUDITE_PRODIGY", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}], "totalPoints": 141}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Aldric');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 4, 8, DATE '2026-05-30', 'TREASURE_HUNT',
        'COALITION_OF_THENION', 'SAND_KINGDOMS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "NIGHTSHADE", "leader": true, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}, {"item": "MUFFLED_MOVEMENT", "reduced": false}]}, {"unit": "ONITAOSHI", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}, {"item": "FANGS_OF_TIAMAT", "reduced": false}]}, {"unit": "THAROS_ONE_EYED_WOLF", "leader": false, "items": []}], "totalPoints": 81}', '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "ARCANE_TOME", "reduced": false}, {"item": "CONJURED_RETINUE", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "PERSONAL_GUARD", "reduced": false}]}, {"unit": "SPELLDANCER_VOIDCASTER", "leader": false, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}], "totalPoints": 116}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Fenna');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 5, 3, DATE '2026-06-09', 'MAGIC_STONES',
        'SAND_KINGDOMS', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "SPELLDANCER_VOIDCASTER", "leader": true, "items": []}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": []}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": []}], "totalPoints": 62}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}, {"item": "POISONED_WEAPONS", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": [{"item": "FANGS_OF_TIAMAT", "reduced": false}]}, {"unit": "NIGHTSHADE", "leader": false, "items": [{"item": "FANGS_OF_TIAMAT", "reduced": false}, {"item": "DEVOTION_PAIMON", "reduced": false}]}], "totalPoints": 57}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 2, 7, DATE '2026-06-20', 'TREASURE_HUNT',
        'SAND_KINGDOMS', 'HELIAN_LEAGUE', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": []}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": []}], "totalPoints": 61}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": []}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "GLYPHSCRIBE_REDUCE_WEIGHT", "reduced": false}]}], "totalPoints": 95}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Dara');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 9, 5, DATE '2026-06-28', 'SUPPLY_RUN',
        'EMPIRE_OF_SOGA', 'SAND_KINGDOMS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "CLAN_CHAMPION", "leader": true, "items": []}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": []}, {"unit": "SEIGEN_OF_THE_KESHOBARAI", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "HIRED_BLADE", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}], "totalPoints": 106}', '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": []}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}, {"item": "MANA_CATALYST", "reduced": false}]}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": []}], "totalPoints": 79}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 10, 8, DATE '2026-07-05', 'SUPPLY_RUN',
        'SAND_KINGDOMS', 'GOBLIN_WARTRIBES', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "SPELLDANCER_VOIDCASTER", "leader": true, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "MANA_CATALYST", "reduced": false}]}, {"unit": "VIZIER_OF_CONJURATIONS", "leader": false, "items": []}], "totalPoints": 61}', '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "TROLL_PROWLER", "leader": true, "items": []}, {"unit": "GOBLIN_BRAWLERS", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "GOBLIN_SKIRMISHERS", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "GOBLIN_SHAMAN", "leader": false, "items": []}], "totalPoints": 69}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 4, 5, DATE '2026-07-17', 'TREASURE_HUNT',
        'EMPIRE_OF_SOGA', 'HELIAN_LEAGUE', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        NULL, NULL);
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Brena');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 4, 4, DATE '2026-07-26', 'CLUE_TRAIL',
        'HELIAN_LEAGUE', 'ADVENTURERS_GUILD', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": []}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": [{"item": "TACTICAL_EXPERTISE", "reduced": false}, {"item": "EXPEDITIONARY_TACTICS_SURGE_ORDER", "reduced": false}]}, {"unit": "EXPEDITIONARY_HIEROPHANT", "leader": false, "items": []}, {"unit": "HIRED_BLADE", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}], "totalPoints": 90}', '{"faction": "ADVENTURERS_GUILD", "alliedFaction": null, "units": [{"unit": "AMAZON_GLADIATRIX", "leader": true, "items": []}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": []}, {"unit": "ONITAOSHI", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": [{"item": "POUCH", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}, {"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 147}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Fenna');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 7, 1, DATE '2026-08-01', 'MAGIC_STONES',
        'SAND_KINGDOMS', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "ELEMENTAL_LINEAGE", "reduced": false}, {"item": "CONJURED_RETINUE", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "HIRED_BLADE", "leader": false, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": []}], "totalPoints": 86}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": [{"item": "CLIMBING_EXPERTISE", "reduced": false}, {"item": "FANGS_OF_TIAMAT", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "THAROS_ONE_EYED_WOLF", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 58}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Eryk');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 1, 5, DATE '2026-08-13', 'MAGIC_STONES',
        'SAND_KINGDOMS', 'ONI_CLANS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "FLYING_CARPET", "reduced": false}]}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "ONITAOSHI", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}], "totalPoints": 103}', '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "ONI_MARAUDER", "leader": false, "items": []}, {"unit": "CHIYOHIME", "leader": false, "items": []}, {"unit": "RED_YAKSHA", "leader": false, "items": []}], "totalPoints": 132}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Dara');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 4, 9, DATE '2026-08-19', 'MAGIC_STONES',
        'EMPIRE_OF_SOGA', 'SAND_KINGDOMS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "CLAN_CHAMPION", "leader": true, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": [{"item": "BUJUTSU_EXPERTISE", "reduced": false}]}], "totalPoints": 91}', '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "HIRED_BLADE", "leader": false, "items": [{"item": "FLYING_CARPET", "reduced": false}, {"item": "MANA_CATALYST", "reduced": false}]}, {"unit": "NARA_VEIL_WATCHER", "leader": false, "items": []}, {"unit": "ACADEMY_EXPEDITIONER", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}], "totalPoints": 116}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 3, 3, DATE '2026-08-28', NULL,
        'SAND_KINGDOMS', 'ADVENTURERS_GUILD', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "PERSONAL_GUARD", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": []}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": []}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": []}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 135}', '{"faction": "ADVENTURERS_GUILD", "alliedFaction": null, "units": [{"unit": "RENEGADE_RASETSU", "leader": true, "items": []}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": []}], "totalPoints": 87}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 0, 10, DATE '2026-09-07', 'SNAIL_CHASE',
        'SAND_KINGDOMS', 'HELIAN_LEAGUE', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": []}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": []}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": []}], "totalPoints": 68}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "GIFT_OF_LONGEVITY", "reduced": false}]}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": [{"item": "GIFT_OF_LONGEVITY", "reduced": false}]}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}], "totalPoints": 66}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Aldric');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Tester');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 5, 1, DATE '2026-09-17', 'QUARTER_WAR',
        'COALITION_OF_THENION', 'ADVENTURERS_GUILD', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "NIGHTSHADE", "leader": true, "items": []}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}, {"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "DEVOTION_ANRAS", "reduced": false}]}], "totalPoints": 72}', '{"faction": "ADVENTURERS_GUILD", "alliedFaction": null, "units": [{"unit": "AMAZON_GLADIATRIX", "leader": true, "items": []}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": []}, {"unit": "ONITAOSHI", "leader": false, "items": []}], "totalPoints": 83}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Tester');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Fenna');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 7, 3, DATE '2026-09-27', 'SUPPLY_RUN',
        'SAND_KINGDOMS', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}, {"item": "ELEMENTAL_LINEAGE", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "PERSONAL_GUARD", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": [{"item": "ARCANE_TOME", "reduced": false}]}], "totalPoints": 99}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": []}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": [{"item": "DEVOTION_TIAMAT", "reduced": false}, {"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": []}], "totalPoints": 74}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Cador');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Eryk');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 2, 6, DATE '2026-07-11', 'TREASURE_HUNT',
        'GOBLIN_WARTRIBES', 'ONI_CLANS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "TROLL_PROWLER", "leader": true, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "CHANRA_GOBLIN_SHAMAN", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "GOBLIN_SKIRMISHERS", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "GOBLIN_WARCHIEF", "leader": false, "items": []}, {"unit": "GOBLIN_BRAWLERS", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}], "totalPoints": 106}', '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}, {"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "FORGOTTEN_HERO", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "BONEWALKER", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}, {"item": "UTILITY_TOOL", "reduced": false}]}], "totalPoints": 120}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Cador');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 0, 8, DATE '2026-06-18', 'TREASURE_HUNT',
        'ADVENTURERS_GUILD', 'HELIAN_LEAGUE', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "ADVENTURERS_GUILD", "alliedFaction": null, "units": [{"unit": "MUSHA_BLADEMASTER", "leader": true, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}, {"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": []}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": []}], "totalPoints": 62}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": []}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": []}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": []}], "totalPoints": 59}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Brena');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Dara');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 9, 3, DATE '2026-06-19', 'SNAIL_CHASE',
        'HELIAN_LEAGUE', 'EMPIRE_OF_SOGA', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "COMPANION_OF_HAIRON", "reduced": false}]}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": [{"item": "EXPEDITIONARY_TACTICS_DOUBLE_TIME", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "FLAMEWEAVER_ERRANT", "leader": false, "items": []}], "totalPoints": 71}', '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "CLAN_CHAMPION", "leader": true, "items": []}, {"unit": "KITSUNE_SPELLMAIDEN", "leader": false, "items": []}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": [{"item": "KASSEN_BUKI_DAIKYUU_TSUKAI", "reduced": false}, {"item": "KASSEN_BUKI_KANABOU_TSUKAI", "reduced": false}]}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": [{"item": "KASSEN_BUKI_KANABOU_TSUKAI", "reduced": false}, {"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 112}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Cador');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 5, 5, DATE '2026-07-15', 'QUARTER_WAR',
        'ADVENTURERS_GUILD', 'EMPIRE_OF_SOGA', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "ADVENTURERS_GUILD", "alliedFaction": null, "units": [{"unit": "RENEGADE_RASETSU", "leader": true, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 82}', '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "GREAT_GUARD", "leader": true, "items": []}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": [{"item": "LUCKY_CHARM", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "KASSEN_BUKI_DAIKYUU_TSUKAI", "reduced": false}]}], "totalPoints": 63}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Cador');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Fenna');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 8, 10, DATE '2026-06-29', 'TREASURE_HUNT',
        'GOBLIN_WARTRIBES', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "TROLL_PROWLER", "leader": true, "items": []}, {"unit": "GOBLIN_BRAWLERS", "leader": false, "items": []}, {"unit": "CHANRA_GOBLIN_SHAMAN", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "GOBLIN_SKIRMISHERS", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}, {"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "GOBLIN_WARCHIEF", "leader": false, "items": []}], "totalPoints": 106}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": []}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "ONITAOSHI", "leader": false, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": [{"item": "MUFFLED_MOVEMENT", "reduced": false}]}], "totalPoints": 81}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Brena');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Eryk');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 8, 9, DATE '2026-06-05', 'QUARTER_WAR',
        'HELIAN_LEAGUE', 'ONI_CLANS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": []}, {"unit": "PALADIN_OF_THE_ORDER", "leader": false, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "FLAMEWEAVER_ERRANT", "leader": false, "items": [{"item": "GLYPHSCRIBE_HYPERIA_S_PROVIDENCE", "reduced": false}, {"item": "CAMARADERIE", "reduced": false}]}, {"unit": "ANARI_ERUDITE_PRODIGY", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}], "totalPoints": 123}', '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": [{"item": "POUCH", "reduced": false}]}, {"unit": "ONI_PARIAH", "leader": false, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}, {"item": "ADDITIONAL_PROTECTION", "reduced": false}]}], "totalPoints": 111}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Dara');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 8, 1, DATE '2026-05-14', 'MAGIC_STONES',
        'SAND_KINGDOMS', 'EMPIRE_OF_SOGA', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "THENRIN_SWASHBUCKLER", "leader": true, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": []}, {"unit": "NARA_VEIL_WATCHER", "leader": false, "items": [{"item": "ARCANE_TOME", "reduced": false}]}, {"unit": "VIZIER_OF_CONJURATIONS", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}, {"item": "MANA_CATALYST", "reduced": false}]}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": [{"item": "MANA_CATALYST", "reduced": false}]}], "totalPoints": 120}', '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "GREAT_GUARD", "leader": true, "items": [{"item": "FIRST_AID", "reduced": false}, {"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": []}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": [{"item": "LUCKY_CHARM", "reduced": false}]}, {"unit": "CLAN_CHAMPION", "leader": false, "items": [{"item": "SEASONED_COMBATANT", "reduced": false}]}, {"unit": "HIRED_BLADE", "leader": false, "items": []}], "totalPoints": 123}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Fenna');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Dara');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 10, 0, DATE '2026-08-24', 'TREASURE_HUNT',
        'COALITION_OF_THENION', 'EMPIRE_OF_SOGA', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": []}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "NIGHT_TEMPLE_PRIESTESS", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "NIGHTSHADE", "leader": false, "items": [{"item": "FANGS_OF_TIAMAT", "reduced": false}, {"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 107}', '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "CLAN_CHAMPION", "leader": true, "items": [{"item": "KASSEN_BUKI_NAGAMAKI_TSUKAI", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "MUSHA_BOWMASTER", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": []}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": []}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": []}], "totalPoints": 136}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Aldric');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 7, 4, DATE '2026-09-19', 'SUPPLY_RUN',
        'COALITION_OF_THENION', 'GOBLIN_WARTRIBES', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "NIGHTSHADE", "leader": true, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "HELRIN_EXPATRIATE", "leader": false, "items": [{"item": "DEVOTION_TIAMAT", "reduced": false}]}, {"unit": "LUPUS_REX", "leader": false, "items": []}, {"unit": "BLADEBRETHREN_ELITE", "leader": false, "items": []}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": []}], "totalPoints": 87}', '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "TROLL_PROWLER", "leader": true, "items": []}, {"unit": "GOBLIN_SHAMAN", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "CHANRA_GOBLIN_SHAMAN", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 82}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Fenna');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 2, 7, DATE '2026-04-14', 'TOXIC_INFESTATION',
        'COALITION_OF_THENION', 'COALITION_OF_THENION', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": []}], "totalPoints": 79}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "NIGHTSHADE", "leader": true, "items": [{"item": "POISONED_WEAPONS", "reduced": false}]}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": [{"item": "CLIMBING_EXPERTISE", "reduced": false}]}, {"unit": "GUILDSWORN_KNIGHT", "leader": false, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}], "totalPoints": 110}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Fenna');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Eryk');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 7, 7, DATE '2026-07-12', 'CLUE_TRAIL',
        'COALITION_OF_THENION', 'ONI_CLANS', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": [{"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": [{"item": "MUFFLED_MOVEMENT", "reduced": false}]}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": [{"item": "DEVOTION_ANRAS", "reduced": false}, {"item": "DEVOTION_PAIMON", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": [{"item": "POISONED_WEAPONS", "reduced": false}]}], "totalPoints": 103}', '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": []}, {"unit": "RED_YAKSHA", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}, {"item": "FIRST_AID", "reduced": false}]}, {"unit": "RED_RASETSU", "leader": false, "items": []}, {"unit": "ONI_MARAUDER", "leader": false, "items": []}, {"unit": "BLUE_RASETSU", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}], "totalPoints": 167}');
    SELECT id INTO pa FROM users WHERE lower(display_name) = lower('Fenna');
    SELECT id INTO pb FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), pa, pb, 0, 9, DATE '2026-08-20', 'SNAIL_CHASE',
        'COALITION_OF_THENION', 'ADVENTURERS_GUILD', NULL, '[seed-stats]', 'CONFIRMED', pa, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "LUPUS_REX", "leader": true, "items": []}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": []}, {"unit": "THAROS_ONE_EYED_WOLF", "leader": false, "items": [{"item": "DEVOTION_TIAMAT", "reduced": false}]}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": []}], "totalPoints": 87}', '{"faction": "ADVENTURERS_GUILD", "alliedFaction": null, "units": [{"unit": "TOMOE_ENDLESS_RAIN", "leader": true, "items": []}, {"unit": "MUSHA_BLADEMASTER", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": [{"item": "POUCH", "reduced": false}, {"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "RENEGADE_RASETSU", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}], "totalPoints": 113}');
    RAISE NOTICE 'Dodano % gier (w tym % gracza Tester)', 32, 20;
END $$;
