-- Generated by tools/seed/make_test1_games.py – test data only, do not run in production.
DO $$
DECLARE
    me UUID;
    opp UUID;
    reporter UUID;
BEGIN
    SELECT id INTO me FROM users WHERE lower(display_name) = 'test1';
    IF me IS NULL THEN
        RAISE EXCEPTION 'Brak użytkownika test1 – najpierw załóż konto o tym nicku.';
    END IF;
    DELETE FROM friendly_games WHERE notes = '[seed]' AND (player_a = me OR player_b = me);
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Aldric');
    IF opp IS NULL THEN
        opp := gen_random_uuid();
        INSERT INTO users (id, email, display_name, email_verified_at, locale, created_at, updated_at)
        VALUES (opp, 'seed-aldric@example.invalid', 'Aldric', now(), 'pl', now(), now());
        INSERT INTO user_roles (user_id, role) VALUES (opp, 'USER');
    END IF;
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Brena');
    IF opp IS NULL THEN
        opp := gen_random_uuid();
        INSERT INTO users (id, email, display_name, email_verified_at, locale, created_at, updated_at)
        VALUES (opp, 'seed-brena@example.invalid', 'Brena', now(), 'pl', now(), now());
        INSERT INTO user_roles (user_id, role) VALUES (opp, 'USER');
    END IF;
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Cador');
    IF opp IS NULL THEN
        opp := gen_random_uuid();
        INSERT INTO users (id, email, display_name, email_verified_at, locale, created_at, updated_at)
        VALUES (opp, 'seed-cador@example.invalid', 'Cador', now(), 'pl', now(), now());
        INSERT INTO user_roles (user_id, role) VALUES (opp, 'USER');
    END IF;
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Dara');
    IF opp IS NULL THEN
        opp := gen_random_uuid();
        INSERT INTO users (id, email, display_name, email_verified_at, locale, created_at, updated_at)
        VALUES (opp, 'seed-dara@example.invalid', 'Dara', now(), 'pl', now(), now());
        INSERT INTO user_roles (user_id, role) VALUES (opp, 'USER');
    END IF;
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), opp, me, 7, 7, DATE '2026-09-18', 'QUARTER_WAR',
        'COALITION_OF_THENION', 'ONI_CLANS', NULL, '[seed]', 'CONFIRMED', opp, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "HIRED_BLADE", "leader": true, "items": []}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": []}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": [{"item": "CONCEALED_APPROACH", "reduced": false}, {"item": "CLIMBING_EXPERTISE", "reduced": false}]}], "totalPoints": 69}', '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "RED_RASETSU", "leader": false, "items": []}, {"unit": "BLUE_YAKSHA", "leader": false, "items": []}], "totalPoints": 112}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 6, 4, DATE '2026-09-14', 'TREASURE_HUNT',
        'ONI_CLANS', 'HELIAN_LEAGUE', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "POUCH", "reduced": false}, {"item": "FIRST_AID", "reduced": false}]}, {"unit": "ONI_MARAUDER", "leader": false, "items": []}, {"unit": "RED_YAKSHA", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 108}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "GLYPHSCRIBE_REDUCE_WEIGHT", "reduced": false}]}, {"unit": "FLAMESHAPER", "leader": false, "items": [{"item": "ADEPT_SHAPER", "reduced": false}]}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "SEASONED_COMBATANT", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": [{"item": "EXPEDITIONARY_TACTICS_SURGE_ORDER", "reduced": false}, {"item": "ADDITIONAL_PROTECTION", "reduced": false}]}], "totalPoints": 82}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 4, 9, DATE '2026-09-08', 'SUPPLY_RUN',
        'ONI_CLANS', 'GOBLIN_WARTRIBES', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": []}, {"unit": "BLUE_YAKSHA", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}], "totalPoints": 111}', '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "CHANRA_GOBLIN_SHAMAN", "leader": true, "items": [{"item": "UTILITY_TOOL", "reduced": false}, {"item": "FIRST_AID", "reduced": false}]}, {"unit": "GOBLIN_SHAMAN", "leader": false, "items": []}, {"unit": "TROLL_PROWLER", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}, {"unit": "GOBLIN_WARCHIEF", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}, {"item": "FIRST_AID", "reduced": false}]}], "totalPoints": 107}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Dara');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), opp, me, 4, 1, DATE '2026-08-31', 'SUPPLY_RUN',
        'SAND_KINGDOMS', 'ONI_CLANS', NULL, '[seed]', 'CONFIRMED', opp, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "KOGETSU_CURSED_MONK", "leader": true, "items": []}, {"unit": "HELRIN_EXPATRIATE", "leader": false, "items": []}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": []}], "totalPoints": 62}', '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "VENGEFUL_SPIRIT", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "FORGOTTEN_HERO", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}], "totalPoints": 126}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 9, 2, DATE '2026-08-28', 'SUPPLY_RUN',
        'ONI_CLANS', 'EMPIRE_OF_SOGA', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "POUCH", "reduced": false}, {"item": "CAMARADERIE", "reduced": false}]}, {"unit": "ONI_MARAUDER", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "ONI_PARIAH", "leader": false, "items": [{"item": "POUCH", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}], "totalPoints": 124}', '{"faction": "EMPIRE_OF_SOGA", "alliedFaction": null, "units": [{"unit": "GREAT_GUARD", "leader": true, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "POUCH", "reduced": false}, {"item": "KASSEN_BUKI_KANABOU_TSUKAI", "reduced": false}]}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": []}], "totalPoints": 60}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 5, 5, DATE '2026-08-21', 'TREASURE_HUNT',
        'ONI_CLANS', 'HELIAN_LEAGUE', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "ONI_PARIAH", "leader": false, "items": []}, {"unit": "BONEWALKER", "leader": false, "items": [{"item": "POUCH", "reduced": false}]}], "totalPoints": 137}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "POUCH", "reduced": false}]}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": [{"item": "GLYPHSCRIBE_REDUCE_WEIGHT", "reduced": false}]}, {"unit": "ANARI_ERUDITE_PRODIGY", "leader": false, "items": [{"item": "GLYPHSCRIBE_HYPERIA_S_PROVIDENCE", "reduced": false}]}], "totalPoints": 116}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), opp, me, 0, 0, DATE '2026-08-13', NULL,
        'GOBLIN_WARTRIBES', 'ONI_CLANS', NULL, '[seed]', 'CONFIRMED', opp, now(), now(),
        '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "GOBLIN_SHAMAN", "leader": true, "items": [{"item": "POUCH", "reduced": false}]}, {"unit": "GOBLIN_BRAWLERS", "leader": false, "items": []}, {"unit": "GOBLIN_WARCHIEF", "leader": false, "items": []}], "totalPoints": 55}', '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}, {"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "CHIYOHIME", "leader": false, "items": []}], "totalPoints": 116}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Dara');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 4, 0, DATE '2026-08-08', 'TREASURE_HUNT',
        'SAND_KINGDOMS', 'SAND_KINGDOMS', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "NARA_VEIL_WATCHER", "leader": true, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}, {"item": "MANA_CATALYST", "reduced": false}]}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": [{"item": "ELEMENTAL_LINEAGE", "reduced": false}]}, {"unit": "FARIS_OUTRIDER", "leader": false, "items": [{"item": "ELEMENTAL_LINEAGE", "reduced": false}]}, {"unit": "SLAYER_DRAGOON", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}], "totalPoints": 95}', '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "VIZIER_OF_CONJURATIONS", "leader": true, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "ACADEMY_EXPEDITIONER", "leader": false, "items": [{"item": "UTILITY_TOOL", "reduced": false}, {"item": "CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": [{"item": "ELEMENTAL_LINEAGE", "reduced": false}]}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": [{"item": "CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 113}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 1, 3, DATE '2026-08-02', 'SNAIL_CHASE',
        'ONI_CLANS', 'COALITION_OF_THENION', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "POUCH", "reduced": false}]}, {"unit": "ONI_MARAUDER", "leader": false, "items": []}, {"unit": "FORGOTTEN_HERO", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}, {"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "ONI_PARIAH", "leader": false, "items": []}], "totalPoints": 137}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "SLAYER_DRAGOON", "leader": true, "items": []}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": []}, {"unit": "NIGHTSHADE", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 63}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), opp, me, 8, 2, DATE '2026-07-27', 'CLUE_TRAIL',
        'HELIAN_LEAGUE', 'HELIAN_LEAGUE', NULL, '[seed]', 'CONFIRMED', opp, now(), now(),
        '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "EXPEDITIONARY_TACTICS_DOUBLE_TIME", "reduced": false}]}, {"unit": "EXPEDITIONARY_HIEROPHANT", "leader": false, "items": []}, {"unit": "FLAMEWEAVER_ERRANT", "leader": false, "items": []}], "totalPoints": 68}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "PALADIN_OF_THE_ORDER", "leader": true, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "EXPEDITIONARY_HIEROPHANT", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 82}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 2, 2, DATE '2026-07-22', 'TREASURE_HUNT',
        'HELIAN_LEAGUE', 'GOBLIN_WARTRIBES', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "PALADIN_OF_THE_ORDER", "leader": true, "items": []}, {"unit": "AMAZON_GLADIATRIX", "leader": false, "items": []}, {"unit": "EONIAN_RUNNER", "leader": false, "items": [{"item": "GIFT_OF_LONGEVITY", "reduced": false}]}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": [{"item": "COMPANION_OF_HAIRON", "reduced": false}, {"item": "IMPORTED_CROSSBOW", "reduced": false}]}], "totalPoints": 98}', '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "GOBLIN_SKIRMISHERS", "leader": true, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}, {"unit": "GOBLIN_BRAWLERS", "leader": false, "items": []}, {"unit": "CHANRA_GOBLIN_SHAMAN", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 54}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Dara');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 0, 5, DATE '2026-07-17', 'TREASURE_HUNT',
        'ONI_CLANS', 'SAND_KINGDOMS', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "POUCH", "reduced": false}, {"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}, {"unit": "CHIYOHIME", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}]}], "totalPoints": 120}', '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "EONIAN_RUNNER", "leader": true, "items": []}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": []}, {"unit": "VIZIER_OF_CONJURATIONS", "leader": false, "items": []}], "totalPoints": 67}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), opp, me, 3, 5, DATE '2026-07-09', 'MAGIC_STONES',
        'COALITION_OF_THENION', 'ONI_CLANS', NULL, '[seed]', 'CONFIRMED', opp, now(), now(),
        '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "KOGETSU_CURSED_MONK", "leader": true, "items": [{"item": "POISONED_WEAPONS", "reduced": false}, {"item": "CAMARADERIE", "reduced": false}]}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}, {"item": "CLIMBING_EXPERTISE", "reduced": false}]}, {"unit": "ONITAOSHI", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": [{"item": "MUFFLED_MOVEMENT", "reduced": false}]}], "totalPoints": 103}', '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}, {"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "ONI_MARAUDER", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 116}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 3, 6, DATE '2026-07-04', NULL,
        'ONI_CLANS', 'HELIAN_LEAGUE', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}, {"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "CHIYOHIME", "leader": false, "items": [{"item": "IMPORTED_CASTING_AMPLIFIER", "reduced": false}]}], "totalPoints": 120}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": []}, {"unit": "SCHOLAR_OF_THE_TRUE_WORD", "leader": false, "items": []}, {"unit": "EXPEDITIONARY_HIEROPHANT", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}, {"item": "POUCH", "reduced": false}]}], "totalPoints": 66}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Cador');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 10, 6, DATE '2026-06-28', 'MAGIC_STONES',
        'ONI_CLANS', 'GOBLIN_WARTRIBES', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": []}, {"unit": "BLUE_YAKSHA", "leader": false, "items": [{"item": "IMPORTED_CROSSBOW", "reduced": false}, {"item": "POUCH", "reduced": false}]}], "totalPoints": 116}', '{"faction": "GOBLIN_WARTRIBES", "alliedFaction": null, "units": [{"unit": "GOBLIN_BRAWLERS", "leader": true, "items": [{"item": "CAMARADERIE", "reduced": false}]}, {"unit": "GOBLIN_SKIRMISHERS", "leader": false, "items": []}, {"unit": "CHANRA_GOBLIN_SHAMAN", "leader": false, "items": [{"item": "CAMARADERIE", "reduced": false}]}], "totalPoints": 55}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Dara');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), opp, me, 5, 5, DATE '2026-06-23', 'MAGIC_STONES',
        'SAND_KINGDOMS', 'ONI_CLANS', NULL, '[seed]', 'CONFIRMED', opp, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "SPELLDANCER_AEROTURGE", "leader": true, "items": []}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "HELRIN_EXPATRIATE", "leader": false, "items": [{"item": "KING_OF_THE_BATTLEFIELD", "reduced": false}]}, {"unit": "KOGETSU_CURSED_MONK", "leader": false, "items": []}], "totalPoints": 93}', '{"faction": "ONI_CLANS", "alliedFaction": "UNDEAD", "units": [{"unit": "CHIYOHIME", "leader": true, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}, {"item": "UTILITY_TOOL", "reduced": false}]}, {"unit": "BLUE_YAKSHA", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}], "totalPoints": 118}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Aldric');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 4, 6, DATE '2026-06-14', 'TREASURE_HUNT',
        'ONI_CLANS', 'COALITION_OF_THENION', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "ONI_CLANS", "alliedFaction": null, "units": [{"unit": "BLUE_YAKSHA", "leader": true, "items": []}, {"unit": "RED_RASETSU", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}, {"unit": "ONI_MARAUDER", "leader": false, "items": []}], "totalPoints": 91}', '{"faction": "COALITION_OF_THENION", "alliedFaction": null, "units": [{"unit": "RENEGADE_RASETSU", "leader": true, "items": [{"item": "DEVOTION_PAIMON", "reduced": false}]}, {"unit": "HIRED_BLADE", "leader": false, "items": []}, {"unit": "ONITAOSHI", "leader": false, "items": [{"item": "ADDITIONAL_PROTECTION", "reduced": false}]}], "totalPoints": 68}');
    SELECT id INTO opp FROM users WHERE lower(display_name) = lower('Brena');
    INSERT INTO friendly_games (id, player_a, player_b, small_a, small_b, played_on, scenario_code, faction_a,
        faction_b, league_id, notes, status, reported_by, created_at, decided_at, list_a, list_b)
    VALUES (gen_random_uuid(), me, opp, 10, 7, DATE '2026-06-09', 'QUARTER_WAR',
        'SAND_KINGDOMS', 'HELIAN_LEAGUE', NULL, '[seed]', 'CONFIRMED', me, now(), now(),
        '{"faction": "SAND_KINGDOMS", "alliedFaction": null, "units": [{"unit": "NARA_VEIL_WATCHER", "leader": true, "items": [{"item": "ELEMENTAL_LINEAGE", "reduced": false}]}, {"unit": "TASKMAGE_EXPLORER", "leader": false, "items": [{"item": "FLYING_CARPET", "reduced": false}]}, {"unit": "TOMOE_ENDLESS_RAIN", "leader": false, "items": [{"item": "FLYING_CARPET", "reduced": false}, {"item": "MANA_CATALYST", "reduced": false}]}], "totalPoints": 88}', '{"faction": "HELIAN_LEAGUE", "alliedFaction": null, "units": [{"unit": "FLAMEWEAVER_NOBLE", "leader": true, "items": [{"item": "EXPEDITIONARY_TACTICS_DOUBLE_TIME", "reduced": false}]}, {"unit": "FLAMESHAPER", "leader": false, "items": [{"item": "FIRST_AID", "reduced": false}]}, {"unit": "ANARI_ERUDITE_PRODIGY", "leader": false, "items": [{"item": "ADEPT_SHAPER", "reduced": false}, {"item": "POUCH", "reduced": false}]}, {"unit": "THENRIN_SWASHBUCKLER", "leader": false, "items": []}], "totalPoints": 90}');
    RAISE NOTICE 'Dodano % gier dla test1', 18;
END $$;
